plugins {
    id 'java'
}

group = 'com.harbourpvp'
version = '1.0.8'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

jar {
    archiveBaseName = 'HarbourPVP'
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}
