starting-rating: 0
win-rating: 25
loss-rating: 20
min-rating: 0
placement-matches: 5

tiers:
  HT5: 0
  MT5: 900
  LT5: 1000
  HT4: 1100
  MT4: 1200
  LT4: 1300
  HT3: 1400
  MT3: 1500
  LT3: 1600
  HT2: 1700
  MT2: 1800
  LT2: 1900
  HT1: 2000
  MT1: 2150
  LT1: 2300
kits:
  Sword: {icon: DIAMOND_SWORD, allow-block-place: false, allow-block-break: false}
  Axe: {icon: DIAMOND_AXE, allow-block-place: false, allow-block-break: false}
  Mace: {icon: MACE, allow-block-place: false, allow-block-break: false}
  Pot: {icon: POTION, allow-block-place: false, allow-block-break: false}
  NethPot: {icon: NETHERITE_SWORD, allow-block-place: false, allow-block-break: false}
  SMP: {icon: SHIELD, allow-block-place: true, allow-block-break: true}
  UHC: {icon: GOLDEN_APPLE, allow-block-place: true, allow-block-break: true}
  Vanilla: {icon: END_CRYSTAL, allow-block-place: true, allow-block-break: true}
  Spear: {icon: TRIDENT, allow-block-place: false, allow-block-break: false}
